debug: false

site:
    name: Warehouse
    url: /

database:
    migrations: "warehouse:migrations"

cache:
    browser: false
    varnish: false

paths:
    documentation: data/packagedocs

urls:
    documentation: "https://pythonhosted.org"

security:
    csp:
        default-src:
            - self
        img-src:
            - "*"

logging:
    version: 1
    formatters:
        timeAndLevel:
            format: '%(asctime)s - %(levelname)s: %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: timeAndLevel
            level: DEBUG
            stream: ext://sys.stdout
    loggers:
        warehouse:
            level: INFO
    root:
        level: ERROR
        handlers: [console]
