language: python
python: 3.3

addons:
  postgresql: 9.3

env:
    global:
        - WAREHOUSE_DATABASE_URL=postgresql://postgres@localhost/warehouse
    matrix:
        - TOXENV=py27
        - TOXENV=py33
        - TOXENV=pep8
        - TOXENV=py2pep8
        - TOXENV=docs
        - TOXENV=packaging

install:
    - pip install tox

before_script:
    - psql --version
    - psql -c "CREATE DATABASE warehouse ENCODING 'UTF8';" -U postgres

script:
    - tox

branches:
    only:
        - master

notifications:
    irc:
        channels:
            - "irc.freenode.org#warehouse"
        use_notice: true
        skip_join: true
