debug: true

site:
    name: Warehouse (dev)

database:
    url: "postgresql://localhost/warehouse"
    download_statistics_url: "postgresql://localhost/warehouse"

redis:
    url: "redis://localhost:6379/0"

search:
    hosts:
        - host: 127.0.0.1
          port: 9200

paths:
    documentation: "data/packagedocs"
    packages: "data/packages"

urls:
    documentation: "http://pythonhosted.org/"

logging:
    root:
        level: DEBUG
