debug: true

site:
    name: Warehouse (dev)

database:
    url: "postgresql://localhost/warehouse"
    download_statistics_url: "postgresql://localhost/warehouse"

redis:
    url: "redis://localhost:6379/0"

search:
    hosts:
        - host: 127.0.0.1
          port: 9200

paths:
    documentation: "data/packagedocs"
    packages: "data/packages"

urls:
    documentation: "http://pythonhosted.org/"

security:
    csp:
        default-src:
            - "'self'"
        style-src:
            - "'self'"
            - cloud.typography.com
        font-src:
            - "'self'"
            - "data:"

logging:
    formatters:
        console:
            format: '[%(asctime)s %(levelname)s] %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: console
            level: DEBUG
            stream: ext://sys.stdout
    loggers:
        warehouse:
            level: DEBUG
        elasticsearch:
            level: DEBUG
        elasticsearch.trace:
            level: DEBUG
    root:
        level: INFO
        handlers: [console]
